### ISSUE TITLE
search not working 

### ISSUE THREAD

**Issue by s3bq8** [saarthak08/Twitter-Streaming-App#31]
hi I have done all the required steps but it shows the error

![Capturessssssss](https://user-images.githubusercontent.com/73422594/175363490-4ce17bea-1cb7-4efe-b8c3-ba6014a0e1ac.PNG)

**Comment by s3bq8** [comment]
thank you for replying i use windows just setup front-end 

Front-End directory
I put the keys in a file key.java in Twitter-Streaming-App\Back-End\src\main\java\com\sg\twitterstreaming\config
    Run npm install 
   run npm start
   npm build

but after npm start 
> twitter-streaming@0.1.0 start
> react-scripts start

i ｢wds｣: Project is running at http://192.168.113.1/
i ｢wds｣: webpack output is served from
i ｢wds｣: Content not from webpack is served from C:\Users\df-\Twitter-Streaming-App\Front-End\public
i ｢wds｣: 404s will fallback to /
Starting the development server...
Compiled successfully!

You can now view twitter-streaming in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://192.168.113.1:3000

Note that the development build is not optimized.
To create a production build, use yarn build.

**Comment by saarthak08** [comment]
Hi, 
As per my understanding, you have only setup the frontend in your local machine. You need to setup up both frontend & backend in order to run this project.
After that, I want to see the logs after you try to search.
Thanks
